test_format = 2

[default.args]
domain = "domain.tld"
path = "/globstory"
init_main_permission = "visitors"

[[tests]]
id = "install"
type = "install"

[[tests]]
id = "upgrade-from-1-0-ynh1"
type = "upgrade"
from = "1.0~ynh1"
