#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE INSTALLATION PATH AND DOMAIN
#=================================================
install_dir="$(ensure_install_dir)"
domain="$(ynh_app_setting_get --app="$app" --key=domain)"

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_backup --src_path="$install_dir"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP NGINX CONFIGURATION
#=================================================
ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"
