#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

old_domain="$(ynh_app_setting_get --app="$app" --key=domain)"

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH

#=================================================
# UPDATE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Updating web routing..."
ynh_config_change_url_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app"
