#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# CLEANUP NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX configuration..."
ynh_config_remove_nginx

#=================================================
# FINISH CLEANUP
#=================================================
ynh_script_progression --message="Removal of $app completed"
