#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression "Removing app main directory..."

# Remove the app directory securely
ynh_secure_remove --file="$install_dir"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
