#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# LOAD STORED SETTINGS
#=================================================
install_dir="$(ensure_install_dir)"
domain="$(ynh_app_setting_get --app="$app" --key=domain)"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore_file --origin_path="$install_dir"

# Restore permissions on app files
chown -R "$app":www-data "$install_dir"

#=================================================
# RESTORE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring NGINX configuration..."

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading NGINX web server..."

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
