#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors
pkg_version="$(awk -F'"' '/^version =/ {print $2; exit}' "$pkg_root_dir/manifest.toml")"

#=================================================
# ENSURE PREVIOUS INSTALL VALUES EXIST
#=================================================
ynh_script_progression --message="Loading existing configuration..."
install_dir="$(ensure_install_dir)"
domain="$(ynh_app_setting_get --app="$app" --key=domain)"
path_url="$(ynh_app_setting_get --app="$app" --key=path)"

#=================================================
# UPGRADE APPLICATION FILES
#=================================================
ynh_script_progression --message="Updating application files..."
rsync -a --delete "$pkg_sources_dir/app/" "$install_dir"/
chown -R "$app":www-data "$install_dir"
chmod -R u=rwX,g=rX,o= "$install_dir"

#=================================================
# REFRESH NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Refreshing web server configuration..."
ynh_app_setting_set --app="$app" --key=domain --value="$domain"
ynh_app_setting_set --app="$app" --key=path --value="$path_url"
ynh_config_add_nginx
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# UPDATE PERMISSIONS
#=================================================
ynh_permission_update --permission="main" --url="$path_url"

#=================================================
# FINALISE UPGRADE
#=================================================
ynh_app_setting_set --app="$app" --key=installed_version --value="$pkg_version"
ynh_script_progression --message="Upgrade of $app completed"
